import Head from 'next/head'
import Search from '../components/Search'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dope Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Search />
      </div>
    </div>
  )
}
