import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dope Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='grid place-items-center h-screen'>
        DOPE GOOGLE WITH NEXTJS AND TAILWINDCSS ⚡
      </h1>
    </div>
  )
}
